version: "3.8"
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    working_dir: /usr/src/app
    env_file:
      - .env    
    build: .
    command: uvicorn src.app:app --proxy-headers --host 0.0.0.0 --port 5085
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "8000:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
networks:
  web_network:
    driver: bridge



version: '3'
services:
  core_api:
    build: .
    container_name: "testme"
    ports:
      - "5085:15400"
    volumes:
      - ./app/:/app
