version: "3.8"
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    working_dir: /usr/src/app
    ports:
      - "5085:5085"
    volumes:
      - /usr/src/app
    build: .
    command: uvicorn src.app:app --host 0.0.0.0 --port 5085
