version: "3.8"
services:
  appseed-app:
    build: .
    container_name: appseed_app
    restart: always
    working_dir: /usr/src/app
    ports:
      - "5085:5085"
    env_file:
      - .env    
    command: uvicorn src.app:app --host 0.0.0.0 --port 5085
